data:
  batch_size: 1
  num_workers: 0
  predict_filelist:
  - filepath: /Users/gjb/Desktop/System Audio 20250818 0126.mp3
    output_subdir: .
  transforms_aug:
  - class_path: corruption.corruptions.MultinomialInpaintMaskTransform
    init_args:
      fill_noise_level: 0.5
      inpainting_mask_kwargs:
        is_random: false
        max_inpainting_frac: 0.1013
        min_inpainting_frac: 0.1013
      p_extension_mask: 0.0
      p_inpaint_mask: 0.0
      p_upsample_mask: 1.0
      sampling_rate: 44100
      upsample_mask_kwargs:
        max_cutoff_freq: 12446
        min_cutoff_freq: 12446
  transforms_gt:
  - class_path: audio_transforms.transforms.ComplexSpectrogram
    init_args:
      hop_length: 512
      n_fft: 2048
      win_length: 2048
  - class_path: audio_transforms.transforms.ComplexToMagInstPhase
  - class_path: audio_transforms.transforms.SpectrogramDropDCTerm
  - class_path: audio_transforms.transforms.PowerScaleSpectrogram
    init_args:
      channels:
      - 0
      power: 0.25
